version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: rexponser-gromov-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-telegram_bot}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-telegram_bot}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
